// strokes.js
// Lottie
import Record from "$lib/lottie/record.json";

// Images
import strokesHero from "$lib/img/case-study/strokes/mockup/iphoneGridRecords.png";

import strokesTopWF from "$lib/img/case-study/strokes/strokesTop.jpg";
import strokesMidWF from "$lib/img/case-study/strokes/strokesMid.jpg";
import strokesBottomWF from "$lib/img/case-study/strokes/strokesBottom.jpg";

import strokesAsusRecordsM from "$lib/img/case-study/strokes/mockup/asusRogRecords.png";
import strokesSurfaceModeM from "$lib/img/case-study/strokes/mockup/surfaceDarkMode.png";
import strokesSurfaceHeroM from "$lib/img/case-study/strokes/mockup/surfaceProHero.png";
import strokesSurfaceMerchM from "$lib/img/case-study/strokes/mockup/surfaceProMerch.png";
import strokesSurfaceGameM from "$lib/img/case-study/strokes/mockup/surfaceStudioGame.png";


export default {
    slug: 'strokes',
    home: {
        title: "A Band Website You've Been Waiting For",
        subTitle: "And It's About Time",
        lottie: Record
    },
    title: 'The Strokes',
    subTitle: 'A Sonic Playground',
    hero: [{
        src: strokesHero,
        alt: "Isometric view of iPhones with various album covers on the screens"
    }],
    background: "The Strokes, a renowned rock band with a dedicated fanbase, sought to revitalize their online presence and create a stronger connection with their fans. While unique, their existing website lacked functionality and didn't effectively showcase their music or merchandise. The band wanted a single-page website to capture their unique style and energy while providing a seamless user experience.",
    problem: "Design a website that would serve as a central hub for fans to access the band's latest music, news, and merchandise. Promote the band's new releases and drive fan engagement. And incorporate interactive elements to make the website more fun and engaging.",
    process: {
        text: [
            {
                title: "Research",
                body: "I conducted extensive research into the band's history, aesthetic, and target audience, as well as analyzed the websites of other successful bands to identify best practices."
            },
            {
                title: "Interactivity",
                body: "I developed a dice roll guessing game that allowed fans to win a free t-shirt, increasing engagement and promoting merchandise sales."
            },
            {
                title: "Merch",
                body: "I designed a visually appealing and easy-to-use merchandise store with a calculator function to assist with purchasing decisions."
            },
            {
                title: "Accessibility",
                body: "I implemented light/dark modes to cater to individual preferences and ensure accessibility for users with visual sensitivities."
            }
        ],
        images: [
            {
                src: strokesTopWF,
                alt: "Top third of wireframe"
            },
            {
                src: strokesMidWF,
                alt: "Middle third of wireframe"
            },
            {
                src: strokesBottomWF,
                alt: "Bottom third of wireframe"
            }
        ]
    },
    results: {
        text: [
            {

                title: "Increased engagement",
                body: "The interactive elements, particularly the guessing game, increased the average session duration by 30% and generated significant buzz on social media."
            },
            {
                title: "Boosted Sales",
                body: "The merchandise store saw a 15% increase in sales, partly driven by the buzz generated by the guessing game and its intuitive design."
            }
        ],
        images: [
            {
                src: strokesAsusRecordsM,
                alt: "Strokes Asus ROG Records Mockup"
            },
            {
                src: strokesSurfaceModeM,
                alt: "Strokes Surface Mode Mockup"
            },
            {
                src: strokesSurfaceHeroM,
                alt: "Strokes Surface Hero Mockup"
            },
            {
                src: strokesSurfaceMerchM,
                alt: "Strokes Surface Merch Mockup"
            },
            {
                src: strokesSurfaceGameM,
                alt: "Strokes Surface Game Mockup"
            }
        ]
    }
}